name: flutterApk
on:
  push:
    paths:
      - 'trip_life/**'
      - '.github/**'

defaults:
  run:
    working-directory: ./trip_life

jobs:
  building_apk:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Flutter business
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.1'
      - uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter-install-cache
      - run: flutter pub get
      - run: flutter test
